### PR TITLE
check for undefined

### LINKED ISSUE #6: Crashes when opening a channel
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at getDiscordPronouns (renderer.js?t=1691560591376}:231:28)
    at Pronouns (renderer.js?t=1691560591376}:247:30)
    at Sa (d04e51f80d6748b04472.js:1801:54)
    at Ns (d04e51f80d6748b04472.js:1812:871)
    at Ss (d04e51f80d6748b04472.js:1812:86)
    at gs (d04e51f80d6748b04472.js:1811:618)
    at gu (d04e51f80d6748b04472.js:1858:524)
    at Ic (d04e51f80d6748b04472.js:1848:89)
    at mc (d04e51f80d6748b04472.js:1848:17)
    at hc (d04e51f80d6748b04472.js:1847:867)
    at oc (d04e51f80d6748b04472.js:1844:642)
    at ic (d04e51f80d6748b04472.js:1843:184)
    at v (d04e51f80d6748b04472.js:1960:904)
    at C (d04e51f80d6748b04472.js:1961:267)
    at N.g.<computed> (fa4f55bc08e1824d97dc.js:108:1)
    at m (fa4f55bc08e1824d97dc.js:107:764)
    at MessagePort.M (fa4f55bc08e1824d97dc.js:107:823)```

### PR DESCRIPTION
**Pull request by xPumaa**
resolve #6

### CODE REVIEW

File: src/components/Pronouns.jsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ function getDiscordPronouns(userId, guildId) {
     })
   } else {
     const discordPronouns = getGuildMemberProfile(userId, guildId)?.pronouns || userProfile?.pronouns
-    return discordPronouns.replace(/[\s\u200b]+/g, ' ').trim()
+    return discordPronouns ? discordPronouns.replace(/[\s\u200b]+/g, ' ').trim() : discordPronouns // check for undefined
```
Comment (asportnoy) [inline src/components/Pronouns.jsx:21]: Much easier way to fix this
```suggestion
    return discordPronouns?.replace(/[\s\u200b]+/g, ' ').trim()
```

File: manifest.json
Comment (asportnoy) [inline manifest.json:1]: In general, you shouldn't bump a version for a dev, you should let them do it themselves.
